issuer: http://localhost:15556

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: memries
    redirectURIs:
      - http://localhost:18080/oauth/callback
    name: Memries
    secret: memries-dev-secret

enablePasswordDB: true
staticPasswords:
  # bcrypt of "password" — change for non-dev
  - email: "admin@example.com"
    hash: "$2a$10$3U9SEf30swgNd17eO6G0hO.APdH95xSBigq1uf1zJCk.DI/j1T5Ly"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
